version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: inquirer
    versions:
    - 7.3.3
